# Generated by Django 3.2 on 2021-05-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_string', models.TextField()),
                ('search_string', models.TextField()),
                ('path', models.TextField()),
                ('gatha_num', models.CharField(blank=True, max_length=100, null=True)),
                ('page_num', models.CharField(max_length=100)),
                ('book_num', models.CharField(max_length=50)),
                ('last_update_by', models.CharField(max_length=200)),
                ('last_update_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
