# Generated by Django 3.2 on 2021-06-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idx_search', '0002_alter_indexitem_search_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_string', models.TextField()),
                ('search_result', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_update_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='indexitem',
            name='book_name',
            field=models.TextField(default='test_book_name'),
            preserve_default=False,
        ),
    ]
